name: attacktest
namespace: ""
runtime: quarkus
image: quay.io/ilawson/attacktest
imageDigest: ""
trigger: events
builder: quay.io/boson/faas-quarkus-jvm-builder
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
envVars:
  SCORINGSERVICE: http://scoring-service.battleships-scoring.svc.cluster.local:8080/
  WATCHMAN: http://watchman.battleships-backend.svc.cluster.local:8080/watch
  CARRIER_SCORE: 250
  DESTROYER_SCORE: 50
  SUBMARINE_SCORE: 100
  BATTLESHIP_SCORE: 200
  HIT_SCORE: 5
  PRODMODE: dev
