---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-attack-test
spec:
  broker: default
  filter:
    attributes:
      type: attack
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: attacktest

