---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event2
spec:
  broker: default
  filter:
    attributes:
      type: event2
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: funqtest1

